version: "3.8"

services:
  backend:
    image: ghcr.io/xingrong-chen1/llm-pneumonia-api/backend:latest
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    networks:
      - mynetwork

  frontend:
    image: ghcr.io/xingrong-chen1/llm-pneumonia-api/frontend:latest
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000/api/predict
      - PYTHONPATH=/app
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
