name: backend CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Backend Docker image
        run: |
          docker build -t ghcr.io/xingrong-chen1/llm-pneumonia-api/backend:latest -f backend/dockerfile ./backend
          docker tag ghcr.io/xingrong-chen1/llm-pneumonia-api/backend:latest ghcr.io/xingrong-chen1/llm-pneumonia-api/backend:${{ github.sha }}

      - name: Log in to the registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push the Docker image
        run: |
          docker push ghcr.io/xingrong-chen1/llm-pneumonia-api/backend:${{ github.sha }}
          docker push ghcr.io/xingrong-chen1/llm-pneumonia-api/backend:latest
