name: backend CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Backend Docker image
        run: |
          docker build -t ghcr.io/xingrong-chen1/llm-pneumonia-api/backend:latest -f backend/dockerfile ./backend
          docker tag ghcr.io/xingrong-chen1/llm-pneumonia-api/backend:latest ghcr.io/xingrong-chen1/llm-pneumonia-api/backend:${{ github.sha }}

      - name: Log in to the registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Run Container Structure Tests (CST)
        run: |
          curl -LO https://github.com/GoogleContainerTools/container-structure-test/releases/latest/download/container-structure-test-linux-amd64
          chmod +x container-structure-test-linux-amd64
          sudo mv container-structure-test-linux-amd64 /usr/local/bin/container-structure-test
          container-structure-test test --image ghcr.io/xingrong-chen1/llm-pneumonia-api/backend:${{ github.sha }} --config backend/tests/cst-basic.yaml

      - name: Push the Docker image
        run: |
          docker push ghcr.io/xingrong-chen1/llm-pneumonia-api/backend:${{ github.sha }}
          docker push ghcr.io/xingrong-chen1/llm-pneumonia-api/backend:latest
