name: Build and Push Docker Image frontend

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Frontend Docker image
        run: |
          docker build -t ghcr.io/Xingrong-chen1/LLM-Pneumonia-API/frontend:latest -f frontend/Dockerfile ./frontend
          docker tag ghcr.io/Xingrong-chen1/LLM-Pneumonia-API/frontend:latest ghcr.io/Xingrong-chen1/LLM-Pneumonia-API/frontend:${{ github.sha }}

      - name: Push the Docker image
        run: |
          docker push ghcr.io/Xingrong-chen1/LLM-Pneumonia-API/frontend:${{ github.sha }}
          docker push ghcr.io/Xingrong-chen1/LLM-Pneumonia-API/frontend:latest
